# Generated by Django 6.0.4 on 2026-04-16 20:17

import pdf.helpers
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pdf',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=pdf.helpers.upload_pdf_path)),
            ],
            options={
                'db_table': 'pdf',
            },
        ),
    ]
