# Generated by Django 6.0.4 on 2026-05-17 17:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdf', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Font',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('cmap', models.TextField()),
                ('cmap_name', models.CharField(blank=True, max_length=255)),
                ('pdf', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fonts', to='pdf.pdf')),
            ],
            options={
                'db_table': 'font',
            },
        ),
    ]
